spring:
  application:
    name: account-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mariadb:3306/account?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    initialization-mode: always
    data: classpath:sql/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  mail:
    host: ${{ email-smtp.url }}
    port: 587
    username: userid
    password: password
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  servlet:
    multipart:
      max-file-size: 100MB
server:
  port: 8521

logging:
  level:
    com.virnect.account.application.*: DEBUG

## CORS
cors:
  credentials: false
  allowed-origins: "*"
  allowed-headers: "*"
  allowed-methods: "*"

encrypt:
  key: tLY2kNWrWQMfaRfB3RRbvVKN2LGo6d2n

security:
  jwt-config:
    secret: "&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9"
    access-token-expire: 3600000
    refresh-token-expire: 2592000000
  cookie-domain: "192.168.6.3"
  cookie-path: "/"
  cookieMaxAgeDay: 30

minio:
  access-key: "virnect"
  secret-key: "Qjsprxm13@$"
  server: "http://10.200.0.24:2838"
  bucket: "virnect-platform"


