spring:
  application:
    name: account-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  mail:
    host: ${{ email-smtp.url }}
    port: 587
    username: username
    password: password
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  servlet:
    multipart:
      max-file-size: 100MB
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

server:
  port: 8521

logging:
  level:
    com.virnect.account.*: DEBUG
    org.hibernate.type.descriptor.sql.*: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.200.0.24:8761/eureka
    enabled: false

## CORS
cors:
  credentials: false
  allowed-origins: "*"
  allowed-headers: "*"
  allowed-methods: "*"

encrypt:
  key: tLY2kNWrWQMfaRfB3RRbvVKN2LGo6d2n

security:
  jwt-config:
    secret: "&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9"
    access-token-expire: 3600000
    refresh-token-expire: 2592000000
    invite-token-expire: 86400000
    tract-token-expire: 315360000000
  cookie-domain: "192.168.6.3"
  cookie-path: "/"
  cookieMaxAgeDay: 30

minio:
  access-key: "virnect"
  secret-key: "Qjsprxm13@$"
  server: "http://10.200.0.24:2838"
  bucket: "virnect-platform"


feign:
  autoconfiguration:
    jackson:
      enabled: true

  # feign client url
  squars-studio-api:
    url: ""

  workspace-api:
    url: ""

  contract-api:
    url: ""

  notification-api:
    url: ""

internal:
  workspace:
    url: localhost:8522


hubspot:
  client-id: 29511ecd-dcb9-4453-89d5-67707c0322c8
  client-secret: 170b7965-f36b-4281-847b-9599a0340ffe
  redirect-uri: http://localhost:8080/hubspot
  refresh-token: eu1-616a-a826-4e47-bbc2-0f67924c3da6
  url: https://api.hubapi.com

# services
contract-api:
  ribbon:
    listOfServers: ${contract-api}

workspace-api:
  ribbon:
    listOfServers: ${workspace-api}
