package com.virnect.account.domain.enumclass;

import lombok.Getter;

public enum Mail {
	AUTH_CODE("MAIL_TITLE_OF_AUTH_CODE", "AUTH_CODE"),
	WELCOME("MAIL_TITLE_OF_REGISTER_SUCCESS", "WELCOME"),
	ITEM_PAYMENT_LINK("MAIL_TITLE_OF_ITEM_PAYMENT_LINK", "ITEM_PAYMENT_LINK"),
	ADMIN_ACCOUNT_APPLY("MAIL_TITLE_OF_ADMIN_ACCOUNT_APPLY", "ADMIN_ACCOUNT_APPLY"),
	USER_RESIGN("MAIL_TITLE_OF_USER_RESIGN", "USER_RESIGN"),
	ADMIN_ACCOUNT_APPROVED("MAIL_TITLE_OF_ADMIN_ACCOUNT_APPROVED", "ADMIN_ACCOUNT_APPROVED"),
	GROUP_USER_INVITE("MAIL_TITLE_OF_GROUP_USER_INVITE", "GROUP_USER_INVITE"),
	COUPON_CODE("MAIL_TITLE_OF_COUPON_CODE", "COUPON_CODE"),
	ORGANIZATION_LICENSE_KEY("MAIL_TITLE_OF_ORGANIZATION_LICENSE_KEY", "ORGANIZATION_LICENSE_KEY");

	@Getter
	private String subject;
	@Getter
	private String template;

	Mail(String subject, String template) {
		this.subject = subject;
		this.template = template;
	}
}
