name: test code coverage
on:
  push:
    branches:
      - develop
      - qa
      - staging
      - master
    paths:
      - .github/workflows/test.yml
      - src/**
  pull_request_target:
    branches:
      - develop
      - qa
      - staging
      - master
    paths:
      - .github/workflows/test.yml
      - src/**
    types: [ opened, edited, synchronize ]

jobs: 
  unit-test: # Job id
    runs-on: ubuntu-latest # Runner
    env:
      WORKDIR: .    
    steps:
    - uses: actions/checkout@v2 # Step
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |  
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew jacocoTestReport
    - name: Add to PR comments
      id: jacoco
      uses: madrapps/jacoco-report@v1.4
      with:
        title: 📝 Coverage Report 📝 
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 50
        min-coverage-changed-files: 50
    
